from telegram import Update
from telegram.ext import CallbackContext, Handler, Updater
from tweepy import API
from typing import List
from utils import twitter as twitter_utils

def init_telegram_api(token: str, handlers: List[Handler]) -> Updater:
    r"""Initialize client of Telegram Bot.
    
    Args:
        token (str): Token generated by bot-father to access Telegram Bot.
        handler (List[Handler]): List of handlers to be added to the Bot.
    
    Returns:
        Updater: Client of Telegram Bot
    """
    # Initialize updater of Telegram Bot
    updater = Updater(token=token, use_context=True)

    # Get dispatcher from updater to add handlers to the bot
    dispatcher = updater.dispatcher

    # Add handler to the dispatcher
    for handler in handlers:
        dispatcher.add_handler(handler)

    return updater

def GetTweetsFunc(update: Update, context: CallbackContext, twitter_api: API):
    r"""Get tweets with twitter api for telegram handler.
    
    Args:
        update (Update): Update of telegram bot.
        context (CallbackContext): CallbackContext of telegram bot.
        twitter_api (API): Client of twitter API.
    
    Raises:
        ValueError: if arguments from user inputs doesn't equal to \"hometimeline\".
    """
    # get arguments from context
    args = context.args
    print(args)

    # parse arguments from user
    count = int(args[1])

    argument = str(args[0]).lower()
    if argument == "hometimeline":
        messages = twitter_api.home_timeline(count=count) 
    else:
        raise ValueError("only hometimeline is allowed.")

    text = ""
    for message in messages:
        message = twitter_utils.status_parser(message)
        for k, v in message.items():
            text += str(k) + ": " + str(v)
            text += ", "
        text += "\n"
        text += "------------------------------"
        text += "\n"
    
    # send message
    context.bot.send_message(chat_id=update.effective_chat.id, text=text)
    